name: Mall Web CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.15.0'
      
    - name: INSTALL
      working-directory: ./web/
      run: npm install
    - name: BUILD
      working-directory: ./web/
      run: npm run build
    - name: DEPOLY
      env:
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        mkdir -p ~/.ssh/ && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        scp -o StrictHostKeyChecking=no -r web/dist ubuntu@${HOST}:/home/ubuntu/
        ssh -o StrictHostKeyChecking=no ubuntu@${HOST} "sudo rm -f /usr/local/nginx/html/dist; 
        sudo mv /home/ubuntu/dist /usr/local/nginx/html/; sudo /usr/local/nginx/sbin/nginx -s reload"
